//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntropyRiseStockTP0.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntropyRiseStockTP0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_accept {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_add {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_brick {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_bullet_start {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.bullet_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_bullet_toggle_minus {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.bullet_toggle_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_bullet_toggle_plus {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.bullet_toggle_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_cancel {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_chart_line {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.chart_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_connect {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_database_add {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_database_save {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.database_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_disconnect {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_page_cancel {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.page_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_page_excel {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.page_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_page_white_text_width {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.page_white_text_width", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_picture_empty {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.picture_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_picture_empty1 {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.picture_empty1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_text_list_numbers {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.text_list_numbers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Ext_Net_Build_Ext_Net_icons_tick {
            get {
                object obj = ResourceManager.GetObject("Ext.Net.Build.Ext.Net.icons.tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause_Normal_Red_16px_560489_easyicon_net {
            get {
                object obj = ResourceManager.GetObject("Pause_Normal_Red_16px_560489_easyicon_net", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Start_16px_1186321_easyicon_net {
            get {
                object obj = ResourceManager.GetObject("Start_16px_1186321_easyicon_net", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
